Repository flowcean/flowcean, pull requests merged in 2025-01, with the labels that each got.

#179 Add Filter transform
  pyproject.toml
  src/flowcean/transforms/__init__.py
  src/flowcean/transforms/filter.py
  tests/transforms/test_filter.py
  uv.lock
Labels: transform

#195 Enable just for windows
  justfile
Labels: ci/cd, framework

#98 Match sampling rate reloaded
  examples/ros_offline/run.py
  src/flowcean/transforms/__init__.py
  src/flowcean/transforms/match_sampling_rate.py
  tests/transforms/test_match_sampling_rate.py
Labels: data
